Adding improved error handling.

diff --git a/bin/bcmt b/bin/bcmt
--- a/bin/bcmt
+++ b/bin/bcmt
@@ -1,4 +1,15 @@
 #!/bin/bash
+#utility
+display_usage() {
+    echo "Usage:"
+    echo "${0##*/} [-d] [-r]"
+    exit 1
+}
+die() {
+    echo "ERROR: $* - Aborting."
+    exit 1
+}
+#include
 pushd `dirname $0` > /dev/null
 SCRIPTPATH=`pwd -P`
 popd > /dev/null
@@ -7,27 +18,47 @@ popd > /dev/null
 . $SCRIPTPATH/includes/dumpMeta
 . $SCRIPTPATH/includes/restMeta
 . $SCRIPTPATH/includes/readConf
-do_init $1
-if [ $BCMT_INITOK = "0" ]
+#initialize
+BCMT_INITOK=false
+BCMT_RESTORE=false
+BCMT_DUMP=false
+while getopts dr name
+do
+    case $name in
+        d)
+            $BCMT_RESTORE && die "Cannot dump and restore."
+            BCMT_DUMP=true
+            BCMT_INITOK=true
+            ;;
+        r)
+            $BCMT_DUMP && die "Cannot dump and restore."
+            BCMT_RESTORE=true
+            BCMT_INITOK=true
+            ;;
+        *)
+            echo "Invalid argument specified."
+            display_usage
+            ;;
+    esac
+done
+if [ $BCMT_INITOK = true ]
 then
     do_dbinit
     if [ $BCMT_DBINITOK = "0" ]
     then
         read_tables
-        if [ $BCMT_OPTION = "dump" ]
+        if [ $BCMT_DUMP = true ]
         then
             for table in "${BCMT_TABLES[@]}"; do dump_table $table; done
-        elif [ $BCMT_OPTION = "restore" ]
+        elif [ $BCMT_RESTORE = true ]
         then
             for table in ${BCMT_TABLES[@]}; do restore_table $table; done
         else
-            echo "Unhandled option"
+            die "Invalid operation"
         fi
     else
-        printf "\nCouldn't connect...\n"
+        die "Couldn't connect to database"
     fi
 else
-    echo "Available commands:"
-    echo "dump"
-    echo "restore"
+    display_usage
 fi
