Adding detection for a timed out request

diff --git a/bin/includes/dbinit b/bin/includes/dbinit
--- a/bin/includes/dbinit
+++ b/bin/includes/dbinit
@@ -6,8 +6,18 @@ get_db_pass() {
     stty echo
 }
 attempt_connection() {
-    mysql -u root -p$DBPASS -e exit 2>/dev/null 
-    BCMT_DBINITOK=$?
+    printf "\nAttempting connection to $BCMT_HOST:$BCMT_PORT as user $BCMT_USER..."
+    BCMT_DBINITOK=false
+    timeout 5s mysql -h $BCMT_HOST -P $BCMT_PORT -u $BCMT_USER -p$DBPASS -e exit 2>/dev/null 
+    CONNRESULT=$?
+    if [ $CONNRESULT = "0" ]
+    then
+        BCMT_DBINITOK=true
+        printf " OK\n"
+    else
+        printf " FAIL\n"
+        die "Unable to connect to database"
+    fi
 }
 do_dbinit() {
     get_db_pass
